Disable register
farisfaikar/wayry pull request #18
Opened 2024-10-16 22:25 UTC by Sahib-Aujla

![image](https://github.com/user-attachments/assets/2abbdc1f-72ab-475a-a859-b273d3abde42)

I have disabled register button as well as request to the server endpoint. Please let me know if any changes are required, I will be happy to make them.

2024-10-17 02:05 UTC, farisfaikar requested changes
There are some code changes required that I've reviewed for your code. Please change them accordingly. Happy coding!

2024-10-17 02:05 UTC, farisfaikar commented on components/auth/register-form.tsx
> +import InfoBanner from "./InfoBanner"
- Please use absolute import (using @) instead relative import (using ./)
- Adjust component name to use kebab-case

2024-10-17 02:05 UTC, farisfaikar commented on components/auth/register-form.tsx
> +      <InfoBanner text={"Please use Google/GitHub. Email registeration unavailable!"}/>
Change text to 
```
Please register via Google/GitHub. Email registration currently unavailable!
```
- "register via" instead of "use"
- typo "registeration". Should be "registration" 
- add "currently"

2024-10-17 11:14 UTC, Sahib-Aujla commented
Ok I will make those changes

2024-10-17 17:55 UTC, Sahib-Aujla commented on components/auth/register-form.tsx
> +      <InfoBanner text={"Please use Google/GitHub. Email registeration unavailable!"}/>
![image](https://github.com/user-attachments/assets/f65222ee-8f7d-4dd2-955c-fe0c331908ba)


updated

2024-10-18 04:24 UTC, farisfaikar commented on components/auth/register-form.tsx
> +      <InfoBanner text={"Please use Google/GitHub. Email registeration unavailable!"}/>
Nicely done, thanks!

2024-10-18 04:28 UTC, farisfaikar approved these changes
Looking good, thanks for contributing!

2024-10-18 04:28 UTC, farisfaikar commented on components/auth/register-form.tsx
> +import WarningAlert from "../alerts/warning-alert"
It's still using relative import `..` instead of `@`, but this is a small thing and I will fix it myself

2024-10-18 04:28 UTC, merged